#!/bin/bash

if [ -n "$1" ]; then
  echo "$1" > "token"
  echo "Token: $1 saved to file 'token'"
fi
cwd=$(pwd)
tf="/etc/init.d/telegram-bash-bot"
echo "cwd is $cwd"
echo "">"$tf"
curuser=`whoami`
curgroup=`id -gn "$curuser"`
mkdir -p chats
while IFS='' read -r line || [[ -n "$line" ]]; do
  case $line in
    'DIR=') line=$line$cwd;;
    'USERGROUP=') line=$line$curuser":"$curgroup;;
  esac
  echo "$line">>"$tf"
done < "$cwd/telegram-bash-bot"
cat "$tf"
