#!/bin/bash

if [ -n "$1" ]; then
  echo "$1" > "token"
  echo "Token: $1 saved to file 'token'"
fi
cwd=$(pwd)
tf="/usr/lib/systemd/system/telegram-bash-bot.service"
echo "cwd is $cwd"
echo "">"$tf"
mkdir -p chats
while IFS='' read -r line || [[ -n "$line" ]]; do
  case $line in
    'ExecStart=') line=$line"$cwd/bashbot.sh";;
    'WorkingDirectory=') line=$line"$cwd";;
  esac
  echo "$line">>"$tf"
done < "$cwd/telegram-bash-bot.service"
cat "$tf"
